config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :locations
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode


  validates :address, presence: true
  validates :headline, presence: true
  validates :description, presence: true
  validates :danger_level, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :locations
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

def index
  @locations = Location.all #page that shows the map
end

def new
  @location = Location.new
end

def create
  @location = current_user.locations.create(location_params)
  if @location.valid?
    redirect_to locations_path
  else
    render :new, status: :unprocessable_entity
  end
end

def edit
 @location = Location.find(params[:id])

  if @location.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
  end
end

def update
 @location = Location.find(params[:id])
  if @location.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
  end

 @location.update_attributes(location_params)  
  if @location.valid?
    redirect_to locations_path
  else
    render :edit, status: :unprocessable_entity
  end
end

def destroy
  @location = Location.find(params[:id])
  if @location.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
  end
  @location.destroy
  redirect_to locations_path
end


private

def location_params
 params.require(:location).permit(:address, :headline, :description, :danger_level)
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def index
  @locations = Location.all
end

def new
  @location = Location.new
end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

<body>
  <div id="flex-content-container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="<%= root_path %>">Protest Locator</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Protest Map
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="<%= locations_path =%>">Map</a>
              <a class="dropdown-item" href="<%= new_location_path =%>">Update Map</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              News Sources
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">South China Morning Post</a>
              <a class="dropdown-item" href="#">Hong Kong Free Press</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">MTR</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <% end %>
         </ul>

      </div>
    </nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
    </div>

    <div id="footer">
      <div class="container">
        <div class="row">

          <div class="col-6 col-sm-2">
            <b>About</b>
          </div>
          <div class="col-6 col-sm-2">
            <b>Contact</b>
            <br />
            tobrandonho@gmail.com
            <br />
            +1 (647) 939 2877
          </div>

  </body>
</html>

app/views/locations/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Location</h1>
  <%= simple_form_for @location do |f| %>
    <%= f.input :address %>
    <%= f.input :headline %>
    <%= f.input :description %>
    <%= f.input :danger_level %>
    <%= f.submit 'Edit', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/locations/index.html.erb
  <div id="map"></div>
  <script>

    function initMap() {
      var myLatLng = {lat: -25.363, lng: 131.044};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhTejOmyUuDHavyfvlisrgG5DZKK10qEw&callback=initMap">
  </script>


  <% @locations.each do |location| %>
    <div class="booyah-box col-10 offset-1">
      <div>
        <h1><%= location.address %></h1><br />
        <i><%= location.headline %></i><br />
        <p><%= location.description %></p><br />
        <p><%= location.danger_level %></p><br />
      </div>

      <hr />
      <% if location.user.present? %>
        <small><%= location.user.email %></small>
      <% end %>

    
      <div class="float-right">
        <% if current_user && current_user == location.user %>
          <%= link_to 'Edit', edit_location_path(location), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', location_path(location), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/locations/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @location do |f| %>
    <%= f.input :address %>
    <%= f.input :headline %>
    <%= f.input :description %>
    <%= f.input :danger_level %>
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>